export const utilities = {
  // ১. ডায়নামিক প্রিফিক্স (ভবিষ্যতে কাস্টম [...] ভ্যালু হ্যান্ডেল করার জন্য)
  dynamicPrefixes: {
    'p-': 'padding',
    'py-': ['padding-top', 'padding-bottom'],
    'px-': ['padding-left', 'padding-right'],
    'm-': 'margin',
    'my-': ['margin-top', 'margin-bottom'],
    'mx-': ['margin-left', 'margin-right'],
    "mb-": "margin-bottom",
    "mt-": "margin-top",
    "ml-": "margin-left",
    "mr-": "margin-right",
    "pb-": "padding-bottom",
    "pt-": "padding-top",
    "pl-": "padding-left",
    "pr-": "padding-right",
    "w-": "width",
    "h-": "height",
    "bg-": "background-color",
    'bg-': 'background-color',
    "txt-": {size: "font-size",color: "color"},
    'border-': 'border-color',
    'rounded-': 'border-radius',
    'gap-': 'gap',
    'gap-x-': 'column-gap',
    'gap-y-': 'row-gap',
    'top-': 'top',
    'bottom-': 'bottom',
    'left-': 'left',
    'right-': 'right',
    'line-': 'line-height',
    'blur-': 'filter',
    'bg-blur-': 'backdrop-filter',
    'brightness-': 'filter',
    'bg-brightness-': 'backdrop-filter',
    'opacity-': 'opacity',
    'z-': 'z-index'
  },

  // ২. স্ট্যাটিক ক্লাস (আপনার বানানো ১, ২, ৩ নম্বর ও কালারের সব রেডিমেড ক্লাস এখানে)
  staticClasses: {
    // Reset & Layout Base
    'le-reset': { 'margin': '0 !important', 'padding': '0 !important', 'box-sizing': 'border-box !important' },

    // Padding Helpers
    'p-0': { 'padding': '0 !important' },
    'p-1': { 'padding': 'var(--space-1) !important' },
    'p-2': { 'padding': 'var(--space-2) !important' },
    'p-3': { 'padding': 'var(--space-3) !important' },
    'p-4': { 'padding': 'var(--base) !important' },
    'p-5': { 'padding': 'var(--space-5) !important' },
    'p-6': { 'padding': 'var(--space-6) !important' },
    'p-7': { 'padding': 'var(--space-7) !important' },
    'p-8': { 'padding': 'var(--space-8) !important' },
    'p-9': { 'padding': '5rem !important' },
    'p-10': { 'padding': '6rem !important' },

    'py-0': { 'padding-top': '0 !important', 'padding-bottom': '0 !important' },
    'py-1': { 'padding-top': 'var(--space-1) !important', 'padding-bottom': 'var(--space-1) !important' },
    'py-2': { 'padding-top': 'var(--space-2) !important', 'padding-bottom': 'var(--space-2) !important' },
    'py-3': { 'padding-top': 'var(--space-3) !important', 'padding-bottom': 'var(--space-3) !important' },
    'py-4': { 'padding-top': 'var(--space-4) !important', 'padding-bottom': 'var(--space-4) !important' },
    'py-5': { 'padding-top': 'var(--space-5) !important', 'padding-bottom': 'var(--space-5) !important' },
    'py-6': { 'padding-top': 'var(--space-6) !important', 'padding-bottom': 'var(--space-6) !important' },
    'py-7': { 'padding-top': 'var(--space-7) !important', 'padding-bottom': 'var(--space-7) !important' },
    'py-8': { 'padding-top': 'var(--space-8) !important', 'padding-bottom': 'var(--space-8) !important' },
    'py-9': { 'padding-top': '5rem !important', 'padding-bottom': '5rem !important' },
    'py-10': { 'padding-top': '6rem !important', 'padding-bottom': '6rem !important' },

    'px-0': { 'padding-left': '0 !important', 'padding-right': '0 !important' },
    'px-1': { 'padding-left': 'var(--space-1) !important', 'padding-right': 'var(--space-1) !important' },
    'px-2': { 'padding-left': 'var(--space-2) !important', 'padding-right': 'var(--space-2) !important' },
    'px-3': { 'padding-left': 'var(--space-3) !important', 'padding-right': 'var(--space-3) !important' },
    'px-4': { 'padding-left': 'var(--space-4) !important', 'padding-right': 'var(--space-4) !important' },
    'px-5': { 'padding-left': 'var(--space-5) !important', 'padding-right': 'var(--space-5) !important' },
    'px-6': { 'padding-left': 'var(--space-6) !important', 'padding-right': 'var(--space-6) !important' },
    'px-7': { 'padding-left': 'var(--space-7) !important', 'padding-right': 'var(--space-7) !important' },
    'px-8': { 'padding-left': 'var(--space-8) !important', 'padding-right': 'var(--space-8) !important' },
    'px-9': { 'padding-left': '5rem !important', 'padding-right': '5rem !important' },
    'px-10': { 'padding-left': '6rem !important', 'padding-right': '6rem !important' },

    // Margin Helpers
    'm-0': { 'margin': '0 !important' },
    'm-auto': { 'margin': '0 auto !important' },
    'm-1': { 'margin': 'var(--space-1) !important' },
    'm-2': { 'margin': 'var(--space-2) !important' },
    'm-3': { 'margin': 'var(--space-3) !important' },
    'm-4': { 'margin': 'var(--base) !important' },
    'm-5': { 'margin': 'var(--space-5) !important' },
    'm-6': { 'margin': 'var(--space-6) !important' },
    'm-7': { 'margin': 'var(--space-7) !important' },
    'm-8': { 'margin': 'var(--space-8) !important' },
    'm-9': { 'margin': '5rem !important' },
    'm-10': { 'margin': '6rem !important' },

    'my-0': { 'margin-top': '0 !important', 'margin-bottom': '0 !important' },
    'my-1': { 'margin-top': 'var(--space-1) !important', 'margin-bottom': 'var(--space-1) !important' },
    'my-2': { 'margin-top': 'var(--space-2) !important', 'margin-bottom': 'var(--space-2) !important' },
    'my-3': { 'margin-top': 'var(--space-3) !important', 'margin-bottom': 'var(--space-3) !important' },
    'my-4': { 'margin-top': 'var(--space-4) !important', 'margin-bottom': 'var(--space-4) !important' },
    'my-5': { 'margin-top': 'var(--space-5) !important', 'margin-bottom': 'var(--space-5) !important' },
    'my-6': { 'margin-top': 'var(--space-6) !important', 'margin-bottom': 'var(--space-6) !important' },
    'my-7': { 'margin-top': 'var(--space-7) !important', 'margin-bottom': 'var(--space-7) !important' },
    'my-8': { 'margin-top': 'var(--space-8) !important', 'margin-bottom': 'var(--space-8) !important' },
    'my-9': { 'margin-top': '5rem !important', 'margin-bottom': '5rem !important' },
    'my-10': { 'margin-top': '6rem !important', 'margin-bottom': '6rem !important' },

    'mx-0': { 'margin-left': '0 !important', 'margin-right': '0 !important' },
    'mx-1': { 'margin-left': 'var(--space-1) !important', 'margin-right': 'var(--space-1) !important' },
    'mx-2': { 'margin-left': 'var(--space-2) !important', 'margin-right': 'var(--space-2) !important' },
    'mx-3': { 'margin-left': 'var(--space-3) !important', 'margin-right': 'var(--space-3) !important' },
    'mx-4': { 'margin-left': 'var(--space-4) !important', 'margin-right': 'var(--space-4) !important' },
    'mx-5': { 'margin-left': 'var(--space-5) !important', 'margin-right': 'var(--space-5) !important' },
    'mx-6': { 'margin-left': 'var(--space-6) !important', 'margin-right': 'var(--space-6) !important' },
    'mx-7': { 'margin-left': 'var(--space-7) !important', 'margin-right': 'var(--space-7) !important' },
    'mx-8': { 'margin-left': 'var(--space-8) !important', 'margin-right': 'var(--space-8) !important' },
    'mx-9': { 'margin-left': '5rem !important', 'margin-right': '5rem !important' },
    'mx-10': { 'margin-left': '6rem !important', 'margin-right': '6rem !important' },

    "mt-1": { "margin-top": "4px" },
    "mt-2": { "margin-top": "8px" },
    "mt-3": { "margin-top": "12px" },
    "mt-4": { "margin-top": "16px" },
    "mt-5": { "margin-top": "20px" },

    "mb-1": { "margin-bottom": "4px" },
    "mb-2": { "margin-bottom": "8px" },
    "mb-3": { "margin-bottom": "12px" },
    "mb-4": { "margin-bottom": "16px" },
    "mb-5": { "margin-bottom": "20px" },

    "ml-1": { "margin-top": "4px" },
    "ml-2": { "margin-top": "8px" },
    "ml-3": { "margin-top": "12px" },
    "ml-4": { "margin-top": "16px" },
    "ml-5": { "margin-top": "20px" },

    "mr-1": { "margin-bottom": "4px" },
    "mr-2": { "margin-bottom": "8px" },
    "mr-3": { "margin-bottom": "12px" },
    "mr-4": { "margin-bottom": "16px" },
    "mr-5": { "margin-bottom": "20px" },
    
    "pt-1": { "padding-top": "4px" },
    "pt-2": { "padding-top": "8px" },
    "pt-3": { "padding-top": "12px" },
    "pt-4": { "padding-top": "16px" },
    "pt-5": { "padding-top": "20px" },

    "pb-1": { "padding-bottom": "4px" },
    "pb-2": { "padding-bottom": "8px" },
    "pb-3": { "padding-bottom": "12px" },
    "pb-4": { "padding-bottom": "16px" },
    "pb-5": { "padding-bottom": "20px" },

    "pl-1": { "padding-left": "4px" },
    "pl-2": { "padding-left": "8px" },
    "pl-3": { "padding-left": "12px" },
    "pl-4": { "padding-left": "16px" },
    "pl-5": { "padding-left": "20px" },

    "pr-1": { "padding-right": "4px" },
    "pr-2": { "padding-right": "8px" },
    "pr-3": { "padding-right": "12px" },
    "pr-4": { "padding-right": "16px" },
    "pr-5": { "padding-right": "20px" },

    // Background Colors
    'bg-primary': { 'background-color': 'var(--primary) !important' },
    'bg-primary-light': { 'background-color': 'var(--primary-light) !important' },
    'bg-primary-deep': { 'background-color': 'var(--primary-deep) !important' },
    'bg-secondary': { 'background-color': 'var(--secondary) !important' },
    'bg-secondary-light': { 'background-color': 'var(--secondary-light) !important' },
    'bg-secondary-deep': { 'background-color': 'var(--secondary-deep) !important' },
    'bg-red': { 'background-color': 'var(--red) !important' },
    'bg-red-light': { 'background-color': 'var(--red-light) !important' },
    'bg-red-deep': { 'background-color': 'var(--red-deep) !important' },
    'bg-blue': { 'background-color': 'var(--blue) !important' },
    'bg-blue-light': { 'background-color': 'var(--blue-light) !important' },
    'bg-blue-deep': { 'background-color': 'var(--blue-deep) !important' },
    'bg-green': { 'background-color': 'var(--green) !important' },
    'bg-green-light': { 'background-color': 'var(--green-light) !important' },
    'bg-green-deep': { 'background-color': 'var(--green-deep) !important' },
    'bg-yellow': { 'background-color': 'var(--yellow) !important' },
    'bg-yellow-light': { 'background-color': 'var(--yellow-light) !important' },
    'bg-yellow-deep': { 'background-color': 'var(--yellow-deep) !important' },
    'bg-purple': { 'background-color': 'var(--purple) !important' },
    'bg-purple-light': { 'background-color': 'var(--purple-light) !important' },
    'bg-purple-deep': { 'background-color': 'var(--purple-deep) !important' },
    'bg-pink': { 'background-color': 'var(--pink) !important' },
    'bg-pink-light': { 'background-color': 'var(--pink-light) !important' },
    'bg-pink-deep': { 'background-color': 'var(--pink-deep) !important' },
    'bg-teal': { 'background-color': 'var(--teal) !important' },
    'bg-teal-light': { 'background-color': 'var(--teel-light) !important' },
    'bg-teal-deep': { 'background-color': 'var(--teal-deep) !important' },
    'bg-cyan': { 'background-color': 'var(--cyan) !important' },
    'bg-cyan-light': { 'background-color': 'var(--cyan-light) !important' },
    'bg-cyan-deep': { 'background-color': 'var(--cyan-deep) !important' },
    'bg-magenta': { 'background-color': 'var(--magenta) !important' },
    'bg-magenta-light': { 'background-color': 'var(--magenta-light) !important' },
    'bg-magenta-deep': { 'background-color': 'var(--magenta-deep) !important' },
    'bg-brown': { 'background-color': 'var(--brown) !important' },
    'bg-brown-light': { 'background-color': 'var(--brown-light) !important' },
    'bg-brown-deep': { 'background-color': 'var(--brown-deep) !important' },
    'bg-indigo': { 'background-color': 'var(--indigo) !important' },
    'bg-indigo-light': { 'background-color': 'var(--indigo-light) !important' },
    'bg-indigo-deep': { 'background-color': 'var(--indigo-deep) !important' },
    'bg-violet': { 'background-color': 'var(--violet) !important' },
    'bg-violet-light': { 'background-color': 'var(--violet-light) !important' },
    'bg-violet-deep': { 'background-color': 'var(--violet-deep) !important' },
    'bg-olive': { 'background-color': 'var(--olive) !important' },
    'bg-olive-light': { 'background-color': 'var(--olive-light) !important' },
    'bg-olive-deep': { 'background-color': 'var(--olive-deep) !important' },
    'bg-white': { 'background-color': 'var(--white) !important' },
    'bg-dark': { 'background-color': 'var(--dark) !important' },
    'bg-black': { 'background-color': '#000 !important' },

    // Text Colors
    'txt-primary': { 'color': 'var(--primary) !important' },
    'txt-primary-light': { 'color': 'var(--primary-light) !important' },
    'txt-primary-deep': { 'color': 'var(--primary-deep) !important' },
    'txt-secondary': { 'color': 'var(--secondary) !important' },
    'txt-secondary-light': { 'color': 'var(--secondary-light) !important' },
    'txt-secondary-deep': { 'color': 'var(--secondary-deep) !important' },
    'txt-red': { 'color': 'var(--red) !important' },
    'txt-red-light': { 'color': 'var(--red-light) !important' },
    'txt-red-deep': { 'color': 'var(--red-deep) !important' },
    'txt-blue': { 'color': 'var(--blue) !important' },
    'txt-blue-light': { 'color': 'var(--blue-light) !important' },
    'txt-blue-deep': { 'color': 'var(--blue-deep) !important' },
    'txt-green': { 'color': 'var(--green) !important' },
    'txt-green-light': { 'color': 'var(--green-light) !important' },
    'txt-green-deep': { 'color': 'var(--green-deep) !important' },
    'txt-yellow': { 'color': 'var(--yellow) !important' },
    'txt-yellow-light': { 'color': 'var(--yellow-light) !important' },
    'txt-yellow-deep': { 'color': 'var(--yellow-deep) !important' },
    'txt-purple': { 'color': 'var(--purple) !important' },
    'txt-purple-light': { 'color': 'var(--purple-light) !important' },
    'txt-purple-deep': { 'color': 'var(--purple-deep) !important' },
    'txt-pink': { 'color': 'var(--pink) !important' },
    'txt-pink-light': { 'color': 'var(--pink-light) !important' },
    'txt-pink-deep': { 'color': 'var(--pink-deep) !important' },
    'txt-teal': { 'color': 'var(--teal) !important' },
    'txt-teal-light': { 'color': 'var(--teel-light) !important' },
    'txt-teal-deep': { 'color': 'var(--teal-deep) !important' },
    'txt-cyan': { 'color': 'var(--cyan) !important' },
    'txt-cyan-light': { 'color': 'var(--cyan-light) !important' },
    'txt-cyan-deep': { 'color': 'var(--cyan-deep) !important' },
    'txt-magenta': { 'color': 'var(--magenta) !important' },
    'txt-magenta-light': { 'color': 'var(--magenta-light) !important' },
    'txt-magenta-deep': { 'color': 'var(--magenta-deep) !important' },
    'txt-brown': { 'color': 'var(--brown) !important' },
    'txt-brown-light': { 'color': 'var(--brown-light) !important' },
    'txt-brown-deep': { 'color': 'var(--brown-deep) !important' },
    'txt-indigo': { 'color': 'var(--indigo) !important' },
    'txt-indigo-light': { 'color': 'var(--indigo-light) !important' },
    'txt-indigo-deep': { 'color': 'var(--indigo-deep) !important' },
    'txt-violet': { 'color': 'var(--violet) !important' },
    'txt-violet-light': { 'color': 'var(--violet-light) !important' },
    'txt-violet-deep': { 'color': 'var(--violet-deep) !important' },
    'txt-olive': { 'color': 'var(--olive) !important' },
    'txt-olive-light': { 'color': 'var(--olive-light) !important' },
    'txt-olive-deep': { 'color': 'var(--olive-deep) !important' },
    'txt-white': { 'color': 'var(--white) !important' },
    'txt-dark': { 'color': 'var(--dark) !important' },
    'txt-black': { 'color': '#000 !important' },

    // Box Shadows
    'shadow-1': { 'box-shadow': '0 1px 2px 0 rgba(0,0,0,0.05) !important' },
    'shadow-2': { 'box-shadow': '0 1px 3px 0 rgba(0,0,0,0.1), 0 1px 2px -1px rgba(0,0,0,0.1) !important' },
    'shadow-3': { 'box-shadow': '0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -2px rgba(0,0,0,0.1) !important' },
    'shadow-4': { 'box-shadow': '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -4px rgba(0,0,0,0.1) !important' },
    'shadow-5': { 'box-shadow': '0 20px 25px -5px rgba(0,0,0,0.1), 0 8px 10px -6px rgba(0,0,0,0.1) !important' },
    'shadow-6': { 'box-shadow': '0 25px 50px -12px rgba(0,0,0,0.25) !important' },
    'shadow-7': { 'box-shadow': 'inset 0 2px 4px 0 rgba(0,0,0,0.05) !important' },
    'shadow-8': { 'box-shadow': '0 0 0 3px rgba(66,153,225,0.5) !important' },
    'shadow-9': { 'box-shadow': '0 4px 12px 0 rgba(0,0,0,0.15) !important' },
    'shadow-10': { 'box-shadow': '0 8px 24px 0 rgba(0,0,0,0.2) !important' },

    // Font Sizes
    'txt-1': { 'font-size': 'var(--xs) !important' },
    'txt-2': { 'font-size': 'var(--sm) !important' },
    'txt-3': { 'font-size': 'var(--base) !important' },
    'txt-4': { 'font-size': 'var(--lg) !important' },
    'txt-5': { 'font-size': 'var(--xl) !important' },
    'txt-6': { 'font-size': 'var(--2xl) !important' },
    'txt-7': { 'font-size': 'var(--3xl) !important' },
    'txt-8': { 'font-size': 'var(--4xl) !important' },
    'txt-9': { 'font-size': 'var(--5xl) !important' },
    'txt-10': { 'font-size': 'var(--6xl) !important' },

    // Font Weights
    'txt-300': { 'font-weight': '300 !important' },
    'txt-400': { 'font-weight': '400 !important' },
    'txt-500': { 'font-weight': '500 !important' },
    'txt-600': { 'font-weight': '600 !important' },
    'txt-700': { 'font-weight': '700 !important' },
    'txt-800': { 'font-weight': '800 !important' },
    'txt-900': { 'font-weight': '900 !important' },
    'txt-bold': { 'font-weight': 'bold !important' },
    'txt-normal': { 'font-weight': 'normal !important' },
    'txt-light': { 'font-weight': 'light !important' },

    // Typography Decoration & Layouts
    'txt-sans': { 'font-family': 'var(--txt-sans) !important' },
    'txt-serif': { 'font-family': 'var(--txt-serif) !important' },
    'txt-mono': { 'font-family': 'var(--txt-mono) !important' },
    'txt-italic': { 'font-style': 'italic !important' },
    'txt-non-italic': { 'font-style': 'normal !important' },
    'txt-underline': { 'text-decoration': 'underline !important' },
    'txt-overline': { 'text-decoration': 'overline !important' },
    'txt-none': { 'text-decoration': 'none !important' },
    'txt-solid': { 'text-decoration-style': 'solid !important' },
    'txt-double': { 'text-decoration-style': 'double !important' },
    'txt-dotted': { 'text-decoration-style': 'dotted !important' },
    'txt-dashed': { 'text-decoration-style': 'dashed !important' },
    'txt-wavy': { 'text-decoration-style': 'wavy !important' },

    // Letter Spacings
    'txt-short': { 'letter-spacing': '0.5px' },
    'txt-base': { 'letter-spacing': '1px' },
    'txt-mid': { 'letter-spacing': '1.5px' },
    'txt-long': { 'letter-spacing': '2.5px' },

    // Line Heights
    'line-1': { 'line-height': '1 !important' },
    'line-2': { 'line-height': '1.25 !important' },
    'line-3': { 'line-height': '1.375 !important' },
    'line-4': { 'line-height': '1.5 !important' },
    'line-5': { 'line-height': '1.625 !important' },
    'line-6': { 'line-height': '1.75 !important' },
    'line-7': { 'line-height': '2 !important' },
    'line-8': { 'line-height': '2.25 !important' },
    'line-9': { 'line-height': '2.5 !important' },
    'line-10': { 'line-height': '3 !important' },

    // Border Widths & Styles
    'border': { 'border': '1px solid currentColor !important' },
    'border-1': { 'border-width': '1px !important' },
    'border-2': { 'border-width': '2px !important' },
    'border-3': { 'border-width': '3px !important' },
    'border-4': { 'border-width': '4px !important' },
    'border-5': { 'border-width': '5px !important' },
    'border-6': { 'border-width': '6px !important' },
    'border-7': { 'border-width': '7px !important' },
    'border-8': { 'border-width': '8px !important' },
    'border-9': { 'border-width': '9px !important' },
    'border-10': { 'border-width': '10px !important' },
    'border-solid': { 'border-style': 'solid !important' },
    'border-dotted': { 'border-style': 'dotted !important' },
    'border-dashed': { 'border-style': 'dashed !important' },
    'border-double': { 'border-style': 'double !important' },
    'border-none': { 'border-style': 'none !important' },
    'border-current': { 'border-color': 'currentColor !important' },
    'outline-none': { 'outline': 'none !important' },
    'outline-current': { 'outline': 'currentColor !important' },

    // Border Colors
    'border-primary': { 'border-color': 'var(--primary) !important' },
    'border-primary-light': { 'border-color': 'var(--primary-light) !important' },
    'border-primary-deep': { 'border-color': 'var(--primary-deep) !important' },
    'border-secondary': { 'border-color': 'var(--secondary) !important' },
    'border-secondary-light': { 'border-color': 'var(--secondary-light) !important' },
    'border-secondary-deep': { 'border-color': 'var(--secondary-deep) !important' },
    'border-red': { 'border-color': 'var(--red) !important' },
    'border-red-light': { 'border-color': 'var(--red-light) !important' },
    'border-red-deep': { 'border-color': 'var(--red-deep) !important' },
    'border-blue': { 'border-color': 'var(--blue) !important' },
    'border-blue-light': { 'border-color': 'var(--blue-light) !important' },
    'border-blue-deep': { 'border-color': 'var(--blue-deep) !important' },
    'border-green': { 'border-color': 'var(--green) !important' },
    'border-green-light': { 'border-color': 'var(--green-light) !important' },
    'border-green-deep': { 'border-color': 'var(--green-deep) !important' },
    'border-yellow': { 'border-color': 'var(--yellow) !important' },
    'border-yellow-light': { 'border-color': 'var(--yellow-light) !important' },
    'border-yellow-deep': { 'border-color': 'var(--yellow-deep) !important' },
    'border-purple': { 'border-color': 'var(--purple) !important' },
    'border-purple-light': { 'border-color': 'var(--purple-light) !important' },
    'border-purple-deep': { 'border-color': 'var(--purple-deep) !important' },
    'border-pink': { 'border-color': 'var(--pink) !important' },
    'border-pink-light': { 'border-color': 'var(--pink-light) !important' },
    'border-pink-deep': { 'border-color': 'var(--pink-deep) !important' },
    'border-teal': { 'border-color': 'var(--teal) !important' },
    'border-teal-light': { 'border-color': 'var(--teel-light) !important' },
    'border-teal-deep': { 'border-color': 'var(--teal-deep) !important' },
    'border-cyan': { 'border-color': 'var(--cyan) !important' },
    'border-cyan-light': { 'border-color': 'var(--cyan-light) !important' },
    'border-cyan-deep': { 'border-color': 'var(--cyan-deep) !important' },
    'border-magenta': { 'border-color': 'var(--magenta) !important' },
    'border-magenta-light': { 'border-color': 'var(--magenta-light) !important' },
    'border-magenta-deep': { 'border-color': 'var(--magenta-deep) !important' },
    'border-brown': { 'border-color': 'var(--brown) !important' },
    'border-brown-light': { 'border-color': 'var(--brown-light) !important' },
    'border-brown-deep': { 'border-color': 'var(--brown-deep) !important' },
    'border-indigo': { 'border-color': 'var(--indigo) !important' },
    'border-indigo-light': { 'border-color': 'var(--indigo-light) !important' },
    'border-indigo-deep': { 'border-color': 'var(--indigo-deep) !important' },
    'border-violet': { 'border-color': 'var(--violet) !important' },
    'border-violet-light': { 'border-color': 'var(--violet-light) !important' },
    'border-violet-deep': { 'border-color': 'var(--violet-deep) !important' },
    'border-olive': { 'border-color': 'var(--olive) !important' },
    'border-olive-light': { 'border-color': 'var(--olive-light) !important' },
    'border-olive-deep': { 'border-color': 'var(--olive-deep) !important' },
    'border-white': { 'border-color': 'var(--white) !important' },
    'border-dark': { 'border-color': 'var(--dark) !important' },
    'border-black': { 'border-color': '#000 !important' },

    // Border Radius
    'rounded': { 'border-radius': '0.3125rem !important' },
    'rounded-1': { 'border-radius': '0.125rem !important' },
    'rounded-2': { 'border-radius': '0.25rem !important' },
    'rounded-3': { 'border-radius': '0.375rem !important' },
    'rounded-4': { 'border-radius': '0.5rem !important' },
    'rounded-5': { 'border-radius': '0.75rem !important' },
    'rounded-6': { 'border-radius': '1rem !important' },
    'rounded-7': { 'border-radius': '1.5rem !important' },
    'rounded-8': { 'border-radius': '2rem !important' },
    'rounded-none': { 'border-radius': '0 !important' },
    'rounded-full': { 'border-radius': '9999px !important' },
    'rounded-half': { 'border-radius': '50% !important' },

    // Width Percentages
    'w': { 'width': '100% !important' },
    'w-1': { 'width': '10% !important' },
    'w-2': { 'width': '20% !important' },
    'w-3': { 'width': '30% !important' },
    'w-4': { 'width': '40% !important' },
    'w-5': { 'width': '50% !important' },
    'w-6': { 'width': '60% !important' },
    'w-7': { 'width': '70% !important' },
    'w-8': { 'width': '80% !important' },
    'w-9': { 'width': '90% !important' },
    'w-10': { 'width': '100% !important' },

    // Min Widths
    'm-w': { 'min-width': '100% !important' },
    'm-w-1': { 'min-width': '10% !important' },
    'm-w-2': { 'min-width': '20% !important' },
    'm-w-3': { 'min-width': '30% !important' },
    'm-w-4': { 'min-width': '40% !important' },
    'm-w-5': { 'min-width': '50% !important' },
    'm-w-6': { 'min-width': '60% !important' },
    'm-w-7': { 'min-width': '70% !important' },
    'm-w-8': { 'min-width': '80% !important' },
    'm-w-9': { 'min-width': '90% !important' },
    'm-w-10': { 'min-width': '100% !important' },
    'w-min-content': { 'min-width': 'min-content !important' },
    'w-fit-content': { 'min-width': 'fit-content !important' },
    'w-max-content': { 'min-width': 'max-content !important' },

    // Max Widths
    'mx-w': { 'max-width': '100% !important' },
    'mx-w-1': { 'max-width': '10% !important' },
    'mx-w-2': { 'max-width': '20% !important' },
    'mx-w-3': { 'max-width': '30% !important' },
    'mx-w-4': { 'max-width': '40% !important' },
    'mx-w-5': { 'max-width': '50% !important' },
    'mx-w-6': { 'max-width': '60% !important' },
    'mx-w-7': { 'max-width': '70% !important' },
    'mx-w-8': { 'max-width': '80% !important' },
    'mx-w-9': { 'max-width': '90% !important' },
    'mx-w-10': { 'max-width': '100% !important' },

    // Heights Helpers
    'h-auto': { 'height': 'auto !important' },
    'h-full': { 'height': '100% !important' },
    'h-page': { 'height': '100vh !important' },
    'h-1': { 'height': '10% !important' },
    'h-2': { 'height': '20% !important' },
    'h-3': { 'height': '30% !important' },
    'h-4': { 'height': '40% !important' },
    'h-5': { 'height': '50% !important' },
    'h-6': { 'height': '60% !important' },
    'h-7': { 'height': '70% !important' },
    'h-8': { 'height': '80% !important' },
    'h-9': { 'height': '90% !important' },
    'h-10': { 'height': '100% !important' },
    'h-min-content': { 'min-height': 'min-content !important' },
    'h-fit-content': { 'min-height': 'fit-content !important' },
    'h-max-content': { 'min-height': 'max-content !important' },

    // Display
    'inline': { 'display': 'inline !important' },
    'i-block': { 'display': 'inline-block !important' },
    'block': { 'display': 'block !important' },
    'f-root': { 'display': 'flow-root !important' },
    'flex': { 'display': 'flex !important' },
    'grid': { 'display': 'grid !important' },
    'i-flex': { 'display': 'inline-flex !important' },
    'i-grid': { 'display': 'inline-grid !important' },
    'table': { 'display': 'table !important' },
    't-col': { 'display': 'table-column !important' },
    't-col-group': { 'display': 'table-column-group !important' },
    't-row': { 'display': 'table-row !important' },
    'none': { 'display': 'none !important' },

    // Flex Direction & Wrap
    'fl-row': { 'flex-direction': 'row !important' },
    'fl-col': { 'flex-direction': 'column !important' },
    'fl-warp': { 'flex-wrap': 'wrap !important' },
    'nowarp': { 'flex-wrap': 'nowrap !important' },
    'fl-auto': { 'flex': 'auto !important' },
    'fl-none': { 'flex': 'none !important' },
    'flex-1': { 'flex': '1 1 0% !important' },
    'flex-grow': { 'flex-grow': '1 !important' },
    'flex-shrink': { 'flex-shrink': '1 !important' },

    // Grid Columns Templates
    'g-col-1': { 'grid-template-columns': 'repeat(1, minmax(0, 1fr)) !important' },
    'g-col-2': { 'grid-template-columns': 'repeat(2, minmax(0, 1fr)) !important' },
    'g-col-3': { 'grid-template-columns': 'repeat(3, minmax(0, 1fr)) !important' },
    'g-col-4': { 'grid-template-columns': 'repeat(4, minmax(0, 1fr)) !important' },
    'g-col-5': { 'grid-template-columns': 'repeat(5, minmax(0, 1fr)) !important' },
    'g-col-6': { 'grid-template-columns': 'repeat(6, minmax(0, 1fr)) !important' },
    'g-col-7': { 'grid-template-columns': 'repeat(7, minmax(0, 1fr)) !important' },
    'g-col-8': { 'grid-template-columns': 'repeat(8, minmax(0, 1fr)) !important' },
    'g-col-9': { 'grid-template-columns': 'repeat(9, minmax(0, 1fr)) !important' },
    'g-col-10': { 'grid-template-columns': 'repeat(10, minmax(0, 1fr)) !important' },
    'g-col-11': { 'grid-template-columns': 'repeat(11, minmax(0, 1fr)) !important' },
    'g-col-12': { 'grid-template-columns': 'repeat(12, minmax(0, 1fr)) !important' },
    'g-col-auto': { 'grid-template-columns': 'auto !important' },

    // Grid Column Spans
    'col-span-full': { 'grid-column': '1 / -1 !important' },
    'col-span-1': { 'grid-column': 'span 1 / span 1 !important' },
    'col-span-2': { 'grid-column': 'span 2 / span 2 !important' },
    'col-span-3': { 'grid-column': 'span 3 / span 3 !important' },
    'col-span-4': { 'grid-column': 'span 4 / span 4 !important' },
    'col-span-5': { 'grid-column': 'span 5 / span 5 !important' },
    'col-span-6': { 'grid-column': 'span 6 / span 6 !important' },
    'col-span-7': { 'grid-column': 'span 7 / span 7 !important' },
    'col-span-8': { 'grid-column': 'span 8 / span 8 !important' },
    'col-span-9': { 'grid-column': 'span 9 / span 9 !important' },
    'col-span-10': { 'grid-column': 'span 10 / span 10 !important' },
    'col-span-11': { 'grid-column': 'span 11 / span 11 !important' },
    'col-span-12': { 'grid-column': 'span 12 / span 12 !important' },
    'col-span-auto': { 'grid-column': 'auto !important' },

    // Grid Rows Templates
    'g-row-1': { 'grid-template-rows': 'repeat(1, minmax(0, 1fr)) !important' },
    'g-row-2': { 'grid-template-rows': 'repeat(2, minmax(0, 1fr)) !important' },
    'g-row-3': { 'grid-template-rows': 'repeat(3, minmax(0, 1fr)) !important' },
    'g-row-4': { 'grid-template-rows': 'repeat(4, minmax(0, 1fr)) !important' },
    'g-row-5': { 'grid-template-rows': 'repeat(5, minmax(0, 1fr)) !important' },
    'g-row-6': { 'grid-template-rows': 'repeat(6, minmax(0, 1fr)) !important' },
    'g-row-7': { 'grid-template-rows': 'repeat(7, minmax(0, 1fr)) !important' },
    'g-row-8': { 'grid-template-rows': 'repeat(8, minmax(0, 1fr)) !important' },
    'g-row-9': { 'grid-template-rows': 'repeat(9, minmax(0, 1fr)) !important' },
    'g-row-10': { 'grid-template-rows': 'repeat(10, minmax(0, 1fr)) !important' },
    'g-row-auto': { 'grid-template-rows': 'auto !important' },

    // Gap Control
    'gap-none': { 'gap': '0 !important' },
    'gap-1': { 'gap': '0.25rem !important' },
    'gap-2': { 'gap': '0.5rem !important' },
    'gap-3': { 'gap': '0.75rem !important' },
    'gap-4': { 'gap': '1rem !important' },
    'gap-5': { 'gap': '1.25rem !important' },
    'gap-6': { 'gap': '1.5rem !important' },
    'gap-7': { 'gap': '1.75rem !important' },
    'gap-8': { 'gap': '2rem !important' },
    'gap-9': { 'gap': '2.5rem !important' },
    'gap-10': { 'gap': '3rem !important' },

    'gap-x-1': { 'column-gap': '0.25rem !important' },
    'gap-x-2': { 'column-gap': '0.5rem !important' },
    'gap-x-3': { 'column-gap': '0.75rem !important' },
    'gap-x-4': { 'column-gap': '1rem !important' },
    'gap-x-5': { 'column-gap': '1.25rem !important' },
    'gap-x-6': { 'column-gap': '1.5rem !important' },
    'gap-x-7': { 'column-gap': '1.75rem !important' },
    'gap-x-8': { 'column-gap': '2rem !important' },
    'gap-x-9': { 'column-gap': '2.5rem !important' },
    'gap-x-10': { 'column-gap': '3rem !important' },

    'gap-y-1': { 'row-gap': '0.25rem !important' },
    'gap-y-2': { 'row-gap': '0.5rem !important' },
    'gap-y-3': { 'row-gap': '0.75rem !important' },
    'gap-y-4': { 'row-gap': '1rem !important' },
    'gap-y-5': { 'row-gap': '1.25rem !important' },
    'gap-y-6': { 'row-gap': '1.5rem !important' },
    'gap-y-7': { 'row-gap': '1.75rem !important' },
    'gap-y-8': { 'row-gap': '2rem !important' },
    'gap-y-9': { 'row-gap': '2.5rem !important' },
    'gap-y-10': { 'row-gap': '3rem !important' },

    // Justify & Alignments
    'flex-start': { 'justify-content': 'flex-start !important' },
    'flex-end': { 'justify-content': 'flex-end !important' },
    'jus-center': { 'justify-content': 'center !important' },
    'jus-between': { 'justify-content': 'space-between !important' },
    'jus-around': { 'justify-content': 'space-around !important' },
    'jus-left': { 'justify-content': 'left !important' },
    'jus-right': { 'justify-content': 'right !important' },
    'jus-stretch': { 'justify-content': 'stretch !important' },
    'jus-normal': { 'justify-content': 'normal !important' },
    'self-auto': { 'justify-self': 'auto !important' },
    'cont-center': { 'align-content': 'center !important' },
    'cont-around': { 'align-content': 'space-around !important' },
    'cont-between': { 'align-content': 'space-between !important' },
    'align-center': { 'align-items': 'center !important' },
    'align-f-end': { 'align-items': 'flex-end !important' },
    'align-self-auto': { 'align-self': 'auto !important' },
    'align-self-start': { 'align-self': 'flex-start !important' },
    'place-center': { 'place-content': 'center !important' },
    'place-between': { 'place-content': 'space-between !important' },

    // Typography Settings
    'txt-inherit': { 'color': 'inherit !important' },
    'txt-current': { 'color': 'currentColor !important' },
    'txt-trnasparent': { 'color': 'transparent !important' },
    'txt-hidden': { 'overflow': 'hidden !important', 'text-overflow': 'ellipsis !important', 'white-space': 'nowrap !important' },
    'txt-clip': { 'text-overflow': 'clip !important' },
    'txt-ell': { 'text-overflow': 'ellipsis !important' },
    'txt-wrap': { 'text-wrap': 'wrap !important' },
    'txt-center': { 'text-align': 'center !important' },
    'txt-left': { 'text-align': 'left !important' },
    'txt-right': { 'text-align': 'right !important' },
    'txt-nowrap': { 'text-wrap': 'nowrap !important' },
    'align-base': { 'vertical-align': 'baseline !important' },
    'align-middle': { 'vertical-align': 'middle !important' },
    'align-top': { 'vertical-align': 'top !important' },
    'align-bottom': { 'vertical-align': 'bottom !important' },
    'no-content': { 'content': 'none !important' },

    // Background Controls
    'bg-fix': { 'background-attachment': 'fixed !important' },
    'bg-scroll': { 'background-attachment': 'scroll !important' },
    'bg-inherit': { 'background-color': 'inherit !important' },
    'bg-current': { 'background-color': 'currentColor !important' },
    'bg-transparent': { 'background-color': 'transparent !important' },
    'bg-none': { 'background-image': 'none !important' },
    'bg-png': { 'background-image': 'url(images/bg.png) !important' },
    'bg-norepeat': { 'background-repeat': 'no-repeat !important' },

    // Gradients
    'liner-1': { 'background': 'var(--lin-1) !important' },
    'liner-2': { 'background': 'var(--lin-2) !important' },
    'liner-3': { 'background': 'var(--lin-3) !important' },
    'liner-4': { 'background': 'var(--lin-4) !important' },
    'liner-5': { 'background': 'var(--lin-5) !important' },
    'radial-1': { 'background': 'var(--radi-1) !important' },
    'radial-2': { 'background': 'var(--radi-2) !important' },
    'radial-3': { 'background': 'var(--radi-3) !important' },

    // Opacity Helpers
    'opacity-1': { 'opacity': '0.1 !important' },
    'opacity-2': { 'opacity': '0.2 !important' },
    'opacity-3': { 'opacity': '0.3 !important' },
    'opacity-4': { 'opacity': '0.4 !important' },
    'opacity-5': { 'opacity': '0.5 !important' },
    'opacity-6': { 'opacity': '0.6 !important' },
    'opacity-7': { 'opacity': '0.7 !important' },
    'opacity-8': { 'opacity': '0.8 !important' },
    'opacity-9': { 'opacity': '0.9 !important' },
    'opacity-10': { 'opacity': '1 !important' },

    // Backdrop Filters & Blurs
    'bg-blur-1': { 'backdrop-filter': 'blur(1px) !important' },
    'bg-blur-2': { 'backdrop-filter': 'blur(4px) !important' },
    'bg-blur-3': { 'backdrop-filter': 'blur(8px) !important' },
    'bg-blur-4': { 'backdrop-filter': 'blur(12px) !important' },
    'bg-blur-5': { 'backdrop-filter': 'blur(16px) !important' },
    'bg-blur-6': { 'backdrop-filter': 'blur(20px) !important' },
    'bg-blur-7': { 'backdrop-filter': 'blur(24px) !important' },
    'bg-blur-8': { 'backdrop-filter': 'blur(32px) !important' },
    'bg-blur-9': { 'backdrop-filter': 'blur(40px) !important' },
    'bg-blur-10': { 'backdrop-filter': 'blur(64px) !important' },

    'blur-1': { 'filter': 'blur(1px) !important' },
    'blur-2': { 'filter': 'blur(4px) !important' },
    'blur-3': { 'filter': 'blur(8px) !important' },
    'blur-4': { 'filter': 'blur(12px) !important' },
    'blur-5': { 'filter': 'blur(16px) !important' },
    'blur-6': { 'filter': 'blur(20px) !important' },
    'blur-7': { 'filter': 'blur(24px) !important' },
    'blur-8': { 'filter': 'blur(32px) !important' },
    'blur-9': { 'filter': 'blur(40px) !important' },
    'blur-10': { 'filter': 'blur(64px) !important' },

    'brightness-1': { 'filter': 'brightness(0) !important' },
    'brightness-2': { 'filter': 'brightness(0.1) !important' },
    'brightness-3': { 'filter': 'brightness(0.2) !important' },
    'brightness-4': { 'filter': 'brightness(0.3) !important' },
    'brightness-5': { 'filter': 'brightness(0.4) !important' },
    'brightness-6': { 'filter': 'brightness(0.5) !important' },
    'brightness-7': { 'filter': 'brightness(0.7) !important' },
    'brightness-8': { 'filter': 'brightness(0.8) !important' },
    'brightness-9': { 'filter': 'brightness(0.9) !important' },
    'brightness-10': { 'filter': 'brightness(1) !important' },

    'bg-brightness-1': { 'backdrop-filter': 'brightness(0) !important' },
    'bg-brightness-2': { 'backdrop-filter': 'brightness(0.1) !important' },
    'bg-brightness-3': { 'backdrop-filter': 'brightness(0.2) !important' },
    'bg-brightness-4': { 'backdrop-filter': 'brightness(0.3) !important' },
    'bg-brightness-5': { 'backdrop-filter': 'brightness(0.4) !important' },
    'bg-brightness-6': { 'backdrop-filter': 'brightness(0.5) !important' },
    'bg-brightness-7': { 'backdrop-filter': 'brightness(0.7) !important' },
    'bg-brightness-8': { 'backdrop-filter': 'brightness(0.8) !important' },
    'bg-brightness-9': { 'backdrop-filter': 'brightness(0.9) !important' },
    'bg-brightness-10': { 'backdrop-filter': 'brightness(1) !important' },

    'table-layout': { 'table-layout': 'auto !important' },
    'table-fixed': { 'table-layout': 'fixed !important' },

    // Transitions
    'time-1': { 'transition': 'ease-in-out 0.1s !important' },
    'time-2': { 'transition': 'ease-in-out 0.2s !important' },
    'time-3': { 'transition': 'ease-in-out 0.3s !important' },
    'time-4': { 'transition': 'ease-in-out 0.4s !important' },
    'time-5': { 'transition': 'ease-in-out 0.5s !important' },
    'time-6': { 'transition': 'ease-in-out 0.6s !important' },
    'time-7': { 'transition': 'ease-in-out 0.7s !important' },
    'time-8': { 'transition': 'ease-in-out 0.8s !important' },
    'time-9': { 'transition': 'ease-in-out 0.9s !important' },
    'time-10': { 'transition': 'ease-in-out 1s !important' },
    'time-none': { 'transition': 'none !important' },

    // Cursors
    'pointer': { 'cursor': 'pointer !important' },
    'cur-default': { 'cursor': 'default !important' },
    'cur-none': { 'cursor': 'none !important' },
    'cur-wait': { 'cursor': 'wait !important' },
    'cur-txt': { 'cursor': 'text !important' },
    'cur-move': { 'cursor': 'move !important' },
    'cur-help': { 'cursor': 'help !important' },
    'cur-not-allowed': { 'cursor': 'not-allowed !important' },
    'cur-zoom-in': { 'cursor': 'zoom-in !important' },
    'cur-zoom-out': { 'cursor': 'zoom-out !important' },

    // Scroll Control
    'scrol-auto': { 'scroll-behavior': 'auto !important' },
    'scrol-smooth': { 'scroll-behavior': 'smooth !important' },
    'scrollbar-auto': { 'scrollbar-width': 'auto !important' },
    'scrollbar-thin': { 'scrollbar-width': 'thin !important' },
    'scrollbar-none': { 'scrollbar-width': 'none !important' },

    // SVG Control
    'fill-none': { 'fill': 'none !important' },
    'fill-inherit': { 'fill': 'inherit !important' },
    'fill-current': { 'fill': 'currentColor !important' },
    'fill-primary': { 'fill': 'var(--primary)' },
    'fill-transparent': { 'fill': 'transparent !important' },

    // Z-Indices
    'z-min': { 'z-index': '-1 !important' },
    'z-none': { 'z-index': '0 !important' },
    'z-1': { 'z-index': '1 !important' },
    'z-2': { 'z-index': '20 !important' },
    'z-3': { 'z-index': '30 !important' },
    'z-4': { 'z-index': '40 !important' },
    'z-5': { 'z-index': '50 !important' },
    'z-6': { 'z-index': '100 !important' },
    'z-auto': { 'z-index': 'auto !important' },
    'z-9': { 'z-index': '99999999 !important' },

    // Positionings
    'static': { 'position': 'static !important' },
    'sticky': { 'position': 'sticky !important' },
    'fixed': { 'position': 'fixed !important' },
    'absolute': { 'position': 'absolute !important' },
    'relative': { 'position': 'relative !important' },
    'visible': { 'visibility': 'visible !important' },
    'non-hidden': { 'visibility': 'hidden !important' },

    // Object Fits
    'obj-contain': { 'object-fit': 'contain !important' },
    'obj-cover': { 'object-fit': 'cover !important' },
    'obj-fill': { 'object-fit': 'fill !important' },
    'obj-none': { 'object-fit': 'none !important' },
    'obj-scale-down': { 'object-fit': 'scale-down !important' },

    // Overflow Settings
    'over-auto': { 'overflow': 'auto !important' },
    'hidden': { 'overflow': 'hidden !important' },
    'over-visible': { 'overflow': 'visible !important' },
    'over-scroll': { 'overflow': 'scroll !important' },
    'over-x-auto': { 'overflow-x': 'auto !important' },
    'over-x-hidden': { 'overflow-x': 'hidden !important' },
    'over-y-auto': { 'overflow-y': 'auto !important' },
    'over-y-hidden': { 'overflow-y': 'hidden !important' },

    // Absolute Positions Extension
    'top-0': { 'top': '0 !important' },
    'top-1': { 'top': '10% !important' },
    'top-5': { 'top': '50% !important' },
    'top-10': { 'top': '100% !important' },
    'bottom-0': { 'bottom': '0 !important' },
    'bottom-1': { 'bottom': '10% !important' },
    'bottom-5': { 'bottom': '50% !important' },
    'bottom-10': { 'bottom': '100% !important' },
    'left-0': { 'left': '0 !important' },
    'left-1': { 'left': '10% !important' },
    'left-5': { 'left': '50% !important' },
    'left-10': { 'left': '100% !important' },
    'right-0': { 'right': '0 !important' },
    'right-1': { 'right': '10% !important' },
    'right-5': { 'right': '50% !important' },
    'right-10': { 'right': '100% !important' },

    // Selection controls
    'select-none': { 'user-select': 'none !important' },
    'select-text': { 'user-select': 'text !important' },
    'select-all': { 'user-select': 'all !important' },
    'select-auto': { 'user-select': 'auto !important' },
    'pointer-events-none': { 'pointer-events': 'none !important' },
    'pointer-events-auto': { 'pointer-events': 'auto !important' },

    // Lists Layouts Extension
    'list-none': { 'list-style-type': 'none !important' },
    'list-disc': { 'list-style-type': 'disc !important' },
    'list-decimal': { 'list-style-type': 'decimal !important' }
  }
};